"use client";

import { useState, useRef, useEffect } from "react";
import {
    ChefHat, Search, Clock, Users, Star, Sparkles,
    ArrowRight, Globe, Send, Loader2, Utensils, Flame, Volume2, ArrowLeft, CheckCircle2
} from "lucide-react";
import { NavbarClient } from "@/components/layout/NavbarClient";
import { Footer } from "@/components/layout/Footer";
import { useNavbarTranslations } from "@/hooks/useNavbarTranslations";
import type { DietaryGoal } from "@/lib/ai-model";
import { motion, AnimatePresence } from "framer-motion";
import { useDietaryStore } from "@/store/useDietaryStore";
import { generateHowToCookRecipe } from "@/lib/culinary-engine";

export default function HowToCookPage() {
    const navbarTranslations = useNavbarTranslations();
    const { profile, setGoal } = useDietaryStore();
    const [query, setQuery] = useState("");
    const [isGenerating, setIsGenerating] = useState(false);
    const [recipe, setRecipe] = useState<any>(null);
    const [loadingText, setLoadingText] = useState("Gathering ingredients...");
    const [isSpeaking, setIsSpeaking] = useState(false);
    const [isSpeakingHindi, setIsSpeakingHindi] = useState(false);
    const stopRef = useRef(false);
    const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);

    useEffect(() => {
        return () => {
            if (typeof window !== "undefined" && window.speechSynthesis) {
                window.speechSynthesis.cancel();
            }
        };
    }, []);

    const dietaryOptions: { value: DietaryGoal, icon: string, color: string }[] = [
        { value: 'Standard', icon: '🍽️', color: 'bg-zinc-100 text-zinc-600' },
        { value: 'Keto', icon: '🥑', color: 'bg-green-100 text-green-700' },
        { value: 'Vegan', icon: '🌿', color: 'bg-emerald-100 text-emerald-700' },
        { value: 'High Protein', icon: '🥩', color: 'bg-rose-100 text-rose-700' },
        { value: 'Low Carb', icon: '📉', color: 'bg-blue-100 text-blue-700' }
    ];

    const suggestedQueries = [
        { label: "Masala Dosa", icon: "🫓" },
        { label: "Paneer Tikka", icon: "🥘" },
        { label: "Authentic Pad Thai", icon: "🍜" },
        { label: "Classic Margherita", icon: "🍕" },
        { label: "Butter Chicken", icon: "🍛" }
    ];

    const resultRef = useRef<HTMLDivElement>(null);
    const [initialLoadDone, setInitialLoadDone] = useState(false);

    useEffect(() => {
        if (!initialLoadDone && typeof window !== "undefined") {
            setInitialLoadDone(true);
            const params = new URLSearchParams(window.location.search);
            const dish = params.get("dish");
            if (dish) {
                setQuery(dish);
                handleGenerate(null, dish);
            }
        }
    }, [initialLoadDone]);

    const handleGenerate = async (e: React.FormEvent | null, searchDish?: string) => {
        if (e) e.preventDefault();
        const dishToSearch = searchDish || query;
        if (!dishToSearch.trim()) return;

        setIsGenerating(true);
        setRecipe(null);

        // Progress text simulation
        const texts = ["Analyzing flavor profiles...", "Consulting the AI Chef...", "Generating authentic recipe...", "Structuring ingredients...", "Refining Hindi steps..."];
        let i = 0;
        const interval = setInterval(() => {
            setLoadingText(texts[i % texts.length]);
            i++;
        }, 800);

        try {
            // 1) Try real AI generation via Gemini API
            let aiRecipe = null;
            try {
                const res = await fetch("/api/generate-recipe", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ dishName: dishToSearch, dietaryGoal: profile.goal }),
                });
                if (res.ok) {
                    const data = await res.json();
                    // Only use the AI recipe if it was genuinely generated by Gemini (not a fallback)
                    if (data.recipe && data.source === "gemini") {
                        aiRecipe = data.recipe;
                    } else {
                        console.log("AI returned fallback, using local generator instead");
                    }
                }
            } catch {
                // API call failed — will fall back to local generator
                console.log("AI API unavailable, using local generator");
            }

            clearInterval(interval);

            if (aiRecipe) {
                // Use AI-generated recipe
                setRecipe({
                    name: aiRecipe.name,
                    hindi: aiRecipe.hindi || aiRecipe.name,
                    origin: aiRecipe.origin || "Global",
                    description: aiRecipe.description,
                    descriptionHindi: aiRecipe.descriptionHindi || aiRecipe.description,
                    difficulty: aiRecipe.difficulty || "Medium",
                    prepTime: aiRecipe.prepTime || "15 min",
                    cookTime: aiRecipe.cookTime || "25 min",
                    servings: aiRecipe.servings || 4,
                    ingredients: aiRecipe.ingredients || [],
                    ingredientsHindi: aiRecipe.ingredientsHindi || aiRecipe.ingredients || [],
                    steps: aiRecipe.steps || [],
                    tips: aiRecipe.tips || [],
                    tipsHindi: aiRecipe.tipsHindi || aiRecipe.tips || [],
                });
            } else {
                // 2) Fallback: local knowledge-base generator
                const result = generateHowToCookRecipe(dishToSearch, profile.goal, profile);
                setRecipe(result);
            }

            setTimeout(() => {
                resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }, 100);
        } catch (error) {
            console.error(error);
            clearInterval(interval);
        } finally {
            setIsGenerating(false);
        }
    };

    const playVoice = (lang: 'en' | 'hi') => {
        if (!recipe) return;

        if (lang === 'en' && isSpeaking) {
            window.speechSynthesis.cancel();
            setIsSpeaking(false);
            stopRef.current = true;
            return;
        }
        if (lang === 'hi' && isSpeakingHindi) {
            window.speechSynthesis.cancel();
            setIsSpeakingHindi(false);
            stopRef.current = true;
            return;
        }

        window.speechSynthesis.cancel();
        setIsSpeaking(false);
        setIsSpeakingHindi(false);
        stopRef.current = false;

        // Give synthesis a tiny delay to reset properly
        setTimeout(() => {
            if (lang === 'en') setIsSpeaking(true);
            else setIsSpeakingHindi(true);

            const chunks: string[] = [];

            if (lang === 'hi') {
                chunks.push(`${recipe.hindi || recipe.name} बनाने की विधि।`);
                chunks.push(`सामग्री:`);
                if (recipe.ingredientsHindi && recipe.ingredientsHindi.length > 0) {
                    recipe.ingredientsHindi.forEach((ing: string) => chunks.push(`${ing}।`));
                } else if (recipe.ingredients) {
                    recipe.ingredients.forEach((ing: string) => chunks.push(`${ing}।`));
                }

                chunks.push(`निर्देश:`);
                recipe.steps.forEach((s: any, idx: number) => {
                    chunks.push(`स्टेप ${idx + 1}: ${s.hindi}।`);
                });
            } else {
                chunks.push(`How to cook ${recipe.name}.`);
                chunks.push(`Ingredients:`);
                recipe.ingredients.forEach((ing: string) => chunks.push(`${ing}.`));
                chunks.push(`Instructions:`);
                recipe.steps.forEach((s: any, idx: number) => {
                    chunks.push(`Step ${idx + 1}: ${s.english}.`);
                });
            }

            const validChunks = chunks.filter(c => c && c.trim().length > 0);
            let chunkIndex = 0;

            const speakNext = () => {
                if (stopRef.current) return;
                if (chunkIndex >= validChunks.length) {
                    if (lang === 'en') setIsSpeaking(false); else setIsSpeakingHindi(false);
                    return;
                }

                const speech = new SpeechSynthesisUtterance(validChunks[chunkIndex]);
                speech.rate = 0.9;
                utteranceRef.current = speech; // Prevent GC

                let voices = window.speechSynthesis.getVoices();
                if (lang === 'hi') {
                    speech.lang = 'hi-IN';
                    const hindiVoice = voices.find(v => v.lang === 'hi-IN') || voices.find(v => v.lang.startsWith('hi'));
                    if (hindiVoice) speech.voice = hindiVoice;
                } else {
                    speech.lang = 'en-US';
                    const enVoice = voices.find(v => v.lang === 'en-US') || voices.find(v => v.lang === 'en-GB') || voices.find(v => v.lang.startsWith('en'));
                    if (enVoice) speech.voice = enVoice;
                }

                speech.onend = () => {
                    chunkIndex++;
                    // Small delay between chunks to avoid rapid-fire issues
                    setTimeout(speakNext, 100);
                };

                speech.onerror = (e: SpeechSynthesisErrorEvent) => {
                    // "interrupted", "canceled", and empty errors are expected browser noise
                    if (!e.error || e.error === 'interrupted' || e.error === 'canceled') {
                        return;
                    }
                    // On "not-allowed" or "audio-busy", stop gracefully
                    if (lang === 'en') setIsSpeaking(false); else setIsSpeakingHindi(false);
                };

                try {
                    window.speechSynthesis.speak(speech);
                } catch {
                    if (lang === 'en') setIsSpeaking(false); else setIsSpeakingHindi(false);
                }
            };

            // Voices might need time to load in some browsers
            const voices = window.speechSynthesis.getVoices();
            if (!voices || voices.length === 0) {
                const onVoicesChanged = () => {
                    window.speechSynthesis.removeEventListener('voiceschanged', onVoicesChanged);
                    speakNext();
                };
                window.speechSynthesis.addEventListener('voiceschanged', onVoicesChanged);
                // Fallback: if voiceschanged never fires (some browsers), try after delay
                setTimeout(() => {
                    window.speechSynthesis.removeEventListener('voiceschanged', onVoicesChanged);
                    speakNext();
                }, 500);
            } else {
                speakNext();
            }
        }, 50);
    };

    return (
        <div className="min-h-screen bg-background flex flex-col font-sans">
            <NavbarClient translations={navbarTranslations} />

            <main className="flex-1">
                {/* Hero / Search Section */}
                <div className="bg-gradient-to-br from-primary/5 via-background to-background pt-32 pb-20 border-b border-border relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-96 h-96 bg-primary/5 rounded-full blur-3xl -z-10 animate-pulse" />

                    <div className="container mx-auto px-4 text-center max-w-4xl relative">
                        <motion.div
                            initial={{ scale: 0.9, opacity: 0 }}
                            animate={{ scale: 1, opacity: 1 }}
                            className="inline-flex items-center gap-2 px-6 py-2 rounded-full bg-white dark:bg-zinc-900 border border-border shadow-soft text-primary font-black mb-8"
                        >
                            <Flame className="w-5 h-5 fill-current" />
                            AI KITCHEN EXPERT
                        </motion.div>

                        <h1 className="text-5xl md:text-7xl font-black mb-6 text-foreground tracking-tight leading-[1.1]">
                            How Do You Want to <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-orange-500">Cook Today?</span>
                        </h1>

                        <p className="text-xl text-primary font-bold mb-8">आप आज क्या बनाना चाहते हैं?</p>

                        <p className="text-lg md:text-xl text-muted-foreground mb-12 leading-relaxed max-w-2xl mx-auto">
                            Enter any dish name. Our AI model will immediately analyze its profile and generate a professional recipe with accurate ingredients and steps.
                        </p>

                        <form onSubmit={handleGenerate} className="relative max-w-2xl mx-auto group">
                            <div className="absolute inset-y-0 left-6 flex items-center pointer-events-none">
                                <Search className="w-6 h-6 text-muted-foreground group-focus-within:text-primary transition-colors" />
                            </div>
                            <input
                                type="text"
                                value={query}
                                onChange={(e) => setQuery(e.target.value)}
                                placeholder="e.g., Authentic Masala Dosa, Thai Green Curry..."
                                className="w-full pl-16 pr-40 py-6 rounded-[2rem] border-2 border-border focus:border-primary bg-white dark:bg-zinc-900 shadow-xl focus:ring-4 focus:ring-primary/10 outline-none text-xl transition-all"
                            />
                            <button
                                type="submit"
                                disabled={isGenerating || !query.trim()}
                                className="absolute inset-y-2 right-2 px-8 bg-gradient-to-r from-primary to-orange-600 text-white font-black rounded-full shadow-lg hover:shadow-xl hover:-translate-y-0.5 active:translate-y-0 transition-all disabled:opacity-50 disabled:grayscale flex items-center gap-2"
                            >
                                {isGenerating ? <Loader2 className="w-5 h-5 animate-spin" /> : "GENERATE"}
                                <Sparkles className="w-5 h-5" />
                            </button>
                        </form>

                        <div className="mt-12 flex flex-col items-center">
                            <p className="text-sm font-black text-muted-foreground uppercase tracking-widest mb-4">Select Your Dietary Profile</p>
                            <div className="flex flex-wrap justify-center gap-3 mb-8">
                                {dietaryOptions.map((opt) => (
                                    <button
                                        key={opt.value}
                                        onClick={() => setGoal(opt.value)}
                                        className={`px-6 py-3 rounded-2xl font-bold flex items-center gap-2 transition-all border-2 ${profile.goal === opt.value
                                            ? 'border-primary bg-primary/5 text-primary shadow-lg scale-105'
                                            : 'border-border bg-white dark:bg-zinc-800 text-foreground hover:border-primary/30'
                                            }`}
                                    >
                                        <span>{opt.icon}</span>
                                        {opt.value}
                                    </button>
                                ))}
                            </div>
                        </div>

                        <div className="mt-8 flex flex-wrap justify-center gap-3">
                            {suggestedQueries.map((suggest) => (
                                <button
                                    key={suggest.label}
                                    onClick={() => {
                                        setQuery(suggest.label);
                                        handleGenerate(null, suggest.label);
                                    }}
                                    className="px-5 py-2.5 bg-secondary/50 hover:bg-white dark:hover:bg-zinc-800 border border-border/50 rounded-full text-sm font-bold flex items-center gap-2 transition-all hover:shadow-md hover:-translate-y-0.5"
                                >
                                    <span>{suggest.icon}</span>
                                    {suggest.label}
                                </button>
                            ))}
                        </div>
                    </div>
                </div>

                {/* Recipe Output Section */}
                <div className="container mx-auto px-4 py-20" ref={resultRef}>
                    {isGenerating && (
                        <div className="flex flex-col items-center justify-center py-20 space-y-8 animate-pulse">
                            <div className="w-24 h-24 bg-gradient-to-br from-primary to-orange-500 rounded-3xl flex items-center justify-center shadow-2xl">
                                <Loader2 className="w-12 h-12 text-white animate-spin" />
                            </div>
                            <div className="text-center">
                                <h3 className="text-3xl font-black text-foreground mb-2">{loadingText}</h3>
                                <p className="text-muted-foreground font-medium uppercase tracking-[0.2em] text-sm">Fine-tuning the algorithm</p>
                            </div>
                        </div>
                    )}

                    {recipe && (
                        <motion.div
                            initial={{ opacity: 0, y: 30 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="max-w-5xl mx-auto rounded-[3rem] border border-border overflow-hidden shadow-big bg-white dark:bg-zinc-900"
                        >
                            {/* Recipe Header */}
                            <div className="relative h-[400px] flex items-end">
                                <div className="absolute inset-0 bg-gradient-to-br from-primary/80 to-orange-600/90 z-10" />
                                <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=2000&auto=format&fit=crop')] bg-cover bg-center" />

                                <div className="relative z-20 p-12 w-full">
                                    <div className="flex flex-wrap gap-4 mb-6">
                                        <div className="px-5 py-2 bg-white/20 backdrop-blur-md border border-white/20 rounded-full text-white text-xs font-black uppercase tracking-widest">
                                            {recipe.origin}
                                        </div>
                                        <div className="px-5 py-2 bg-white/20 backdrop-blur-md border border-white/20 rounded-full text-white text-xs font-black uppercase tracking-widest flex items-center gap-2">
                                            <Star className="w-3 h-3 fill-white" />
                                            5.0 AI Rated
                                        </div>
                                    </div>

                                    <h2 className="text-6xl font-black text-white mb-2 leading-tight drop-shadow-lg">
                                        {recipe.name}
                                    </h2>
                                    <p className="text-2xl text-white/90 font-bold mb-10">{recipe.hindi}</p>

                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                                        {[
                                            { icon: Clock, label: "Total Time", value: `${parseInt(recipe.prepTime) + parseInt(recipe.cookTime)} min` },
                                            { icon: Users, label: "Servings", value: `${recipe.servings} People` },
                                            { icon: Flame, label: "Difficulty", value: recipe.difficulty },
                                            { icon: Utensils, label: "Calories", value: "350 kcal" }
                                        ].map((stat, idx) => (
                                            <div key={idx} className="bg-black/20 backdrop-blur-xl p-4 rounded-2xl border border-white/10">
                                                <div className="flex items-center gap-2 text-white/70 text-xs font-bold uppercase tracking-widest mb-1">
                                                    <stat.icon className="w-3 h-3" />
                                                    {stat.label}
                                                </div>
                                                <div className="text-white text-lg font-black">{stat.value}</div>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>

                            {/* Controls Bar */}
                            <div className="bg-secondary/30 border-b border-border p-8 flex flex-wrap items-center justify-between gap-6">
                                <div className="flex items-center gap-6">
                                    <button onClick={() => playVoice('en')} className="flex items-center gap-3 px-6 py-3 bg-white dark:bg-zinc-800 border border-border shadow-soft rounded-2xl font-black text-primary hover:scale-105 active:scale-95 transition-all">
                                        <Volume2 className={`w-5 h-5 ${isSpeaking ? 'text-red-500 animate-pulse' : ''}`} />
                                        {isSpeaking ? "STOP AUDIO" : "ENGLISH AUDIO"}
                                    </button>
                                    <button onClick={() => playVoice('hi')} className="flex items-center gap-3 px-6 py-3 bg-white dark:bg-zinc-800 border border-border shadow-soft rounded-2xl font-black text-orange-600 hover:scale-105 active:scale-95 transition-all">
                                        <Volume2 className={`w-5 h-5 ${isSpeakingHindi ? 'text-red-500 animate-pulse' : ''}`} />
                                        {isSpeakingHindi ? "STOP HINDI" : "HINDI AUDIO (हिंदी)"}
                                    </button>
                                </div>
                                <div className="flex items-center gap-2 px-6 py-3 bg-emerald-500/10 text-emerald-600 rounded-2xl font-black">
                                    <CheckCircle2 className="w-5 h-5" />
                                    AI ACCURACY GUARANTEED
                                </div>
                            </div>

                            <div className="grid grid-cols-1 lg:grid-cols-12 gap-0">
                                {/* Ingredients */}
                                <div className="lg:col-span-5 border-r border-border p-12 bg-zinc-50/50 dark:bg-zinc-900/50">
                                    <h3 className="text-3xl font-black mb-8 flex items-center gap-3">
                                        <Utensils className="w-8 h-8 text-primary" />
                                        Ingredients / सामग्री
                                    </h3>
                                    <div className="space-y-4">
                                        {recipe.ingredients.map((ing: string, idx: number) => (
                                            <motion.div
                                                key={idx}
                                                initial={{ opacity: 0, x: -20 }}
                                                animate={{ opacity: 1, x: 0 }}
                                                transition={{ delay: idx * 0.1 }}
                                                className="group p-5 bg-white dark:bg-zinc-800 border border-border/50 rounded-2xl hover:border-primary/50 transition-all hover:shadow-lg"
                                            >
                                                <div className="flex items-start gap-4">
                                                    <div className="w-8 h-8 shrink-0 rounded-full border-2 border-primary/20 flex items-center justify-center text-primary font-black text-sm group-hover:bg-primary group-hover:text-white transition-colors">
                                                        {idx + 1}
                                                    </div>
                                                    <div>
                                                        <p className="font-black text-lg text-foreground mb-1">{ing}</p>
                                                        <p className="text-primary font-bold">{recipe.ingredientsHindi[idx]}</p>
                                                    </div>
                                                </div>
                                            </motion.div>
                                        ))}
                                    </div>
                                </div>

                                {/* Steps */}
                                <div className="lg:col-span-7 p-12">
                                    <h3 className="text-3xl font-black mb-10 flex items-center gap-3">
                                        <ChefHat className="w-8 h-8 text-primary" />
                                        Culinary Steps / निर्देश
                                    </h3>
                                    <div className="space-y-12 relative before:absolute before:top-4 before:left-4 before:bottom-4 before:w-1 before:bg-gradient-to-b before:from-primary/20 before:to-primary/5">
                                        {recipe.steps.map((step: any, idx: number) => (
                                            <motion.div
                                                key={idx}
                                                initial={{ opacity: 0, x: 20 }}
                                                animate={{ opacity: 1, x: 0 }}
                                                transition={{ delay: idx * 0.15 }}
                                                className="relative pl-12 group"
                                            >
                                                <div className="absolute top-0 left-0 w-9 h-9 bg-white dark:bg-zinc-800 border-2 border-primary rounded-full flex items-center justify-center font-black text-primary z-10 group-hover:bg-primary group-hover:text-white transition-all shadow-md">
                                                    {step.step}
                                                </div>
                                                <div className="space-y-3">
                                                    <p className="text-xl font-bold text-foreground leading-relaxed">{step.english}</p>
                                                    <p className="text-lg text-primary font-medium border-l-4 border-primary/10 pl-4 py-1">{step.hindi}</p>
                                                </div>
                                            </motion.div>
                                        ))}
                                    </div>

                                    {/* Chef Tips section */}
                                    <div className="mt-16 p-8 bg-orange-500/5 border border-orange-500/10 rounded-3xl relative overflow-hidden">
                                        <Sparkles className="absolute -top-4 -right-4 w-24 h-24 text-orange-500/10 rotate-12" />
                                        <h4 className="text-xl font-black text-orange-600 mb-6 flex items-center gap-2">
                                            <Sparkles className="w-5 h-5 fill-current" />
                                            CHEF'S PRO TIPS / शेफ के टिप्स
                                        </h4>
                                        <div className="space-y-4">
                                            {recipe.tips.map((tip: string, idx: number) => (
                                                <div key={idx} className="bg-white/50 dark:bg-zinc-800/50 p-4 rounded-2xl">
                                                    <p className="font-bold text-foreground italic mb-1">"{tip}"</p>
                                                    <p className="text-primary text-sm font-bold">"{recipe.tipsHindi[idx]}"</p>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </motion.div>
                    )}
                </div>
            </main>

            <Footer />
        </div>
    );
}
